[package]
name = "reth-bench-bsc"
version = "1.0.0"
edition = "2021"
rust-version = "1.76"
license = "MIT OR Apache-2.0"
description = "BSC-compatible benchmarking for ethereum nodes"
default-run = "reth-bench-bsc"

[dependencies]
# reth from BSC fork
reth-cli-runner = { git = "https://github.com/bnb-chain/reth", rev = "b11687867" }
reth-cli-util = { git = "https://github.com/bnb-chain/reth", rev = "b11687867" }

reth-node-api = { git = "https://github.com/bnb-chain/reth", rev = "b11687867" }
reth-node-core = { git = "https://github.com/bnb-chain/reth", rev = "b11687867" }
reth-primitives-traits = { git = "https://github.com/bnb-chain/reth", rev = "b11687867" }
reth-tracing = { git = "https://github.com/bnb-chain/reth", rev = "b11687867" }

# alloy
alloy-eips = "1.0"
alloy-json-rpc = "1.0" 
alloy-primitives = "1.3"
alloy-provider = { version = "1.0", features = ["engine-api", "reqwest-rustls-tls"], default-features = false }
alloy-pubsub = "1.0"
alloy-rpc-client = "1.0"
alloy-rpc-types-engine = "1.0"
alloy-transport-http = "1.0"
alloy-transport-ipc = "1.0"
alloy-transport-ws = "1.0"
alloy-transport = "1.0"

# reqwest
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls-native-roots"] }

# tower
tower = "0.5"

# tracing
tracing = "0.1"

# serde
serde = { version = "1.0", features = ["derive"] }


# async
async-trait = "0.1"
futures = "0.3"
tokio = { version = "1.0", features = ["sync", "macros", "time", "rt-multi-thread", "fs"] }

# misc
clap = { version = "4.0", features = ["derive", "env"] }
eyre = "0.6"
thiserror = "1.0"


# for writing data
csv = "1.3"



[dev-dependencies]

[features]
default = ["jemalloc"]

asm-keccak = [
    "reth-node-core/asm-keccak",
    "alloy-primitives/asm-keccak",
]

jemalloc = [
    "reth-cli-util/jemalloc",
    "reth-node-core/jemalloc",
]
jemalloc-prof = ["reth-cli-util/jemalloc-prof"]
tracy-allocator = ["reth-cli-util/tracy-allocator"]

min-error-logs = ["tracing/release_max_level_error"]
min-warn-logs = ["tracing/release_max_level_warn"]
min-info-logs = ["tracing/release_max_level_info"]
min-debug-logs = ["tracing/release_max_level_debug"]
min-trace-logs = ["tracing/release_max_level_trace"]

# no-op feature flag for switching between the `optimism` and default functionality in CI matrices
ethereum = []

[[bin]]
name = "reth-bench-bsc"
path = "src/main.rs"
